env:
  global:
os: linux
dist: trusty
sudo: required
language: cpp
compiler:
- gcc
before_install:
- sudo add-apt-repository ppa:openmw/openmw -y
- sudo apt-get update -q
- sudo apt-get install -y cmake
- cmake --version
- sudo apt-get install -y libopenscenegraph-3.4-dev
#- apt-cache search openscenegraph
#- dpkg -L libopenscenegraph-dev
#- export OSGDIR=/usr/
script:
- cmake -DCMAKE_BUILD_TYPE=Release . && make
notifications:
  email:
    recipients:
    - leadcoder@gmail.com
addons:
  coverity_scan:
    project:
      name: "leadcoder/osgVegetation"
      description: "osgVegetation"
    notification_email: leadcoder@gmail.com.com
    build_command_prepend: cmake -DCMAKE_BUILD_TYPE=Release
    build_command: make -j3
